### ISSUE TITLE
No color Decisions

### ISSUE THREAD

**Issue by ArrowThief** [walter-arrighetti/edl2cdl#1]
Hello, 
I'm a VFX compositor at a small company and we are working on a project that requires us to return colored footage. This is our first client that wanted things returned in this way, so I looked around and found your script. 
My client sent me a EDL exported from AVID, but whenever I try to convert it to CDLs I get "No Color decisions found in EDL file "Bob.edl" Quitting".  Looking inside the EDL I can see color data so I know its there, I'm just not sure how to make it visible to the script. 
I also messed around with things and exported an EDL from Premier and was then able to get a CDL out of it, but the file name was only the first letter of the clip name. So my exported CDL was named D.cdl rather than its full name.   
Thanks for the help
-N

**Comment by heavyimage** [comment]
Hey @ArrowThief -- I know this is nearly 4 years later but I just encountered the same problem.  The issue was that the regexes in @walter-arrighetti's code didn't match up to the EDLs we received and as such it was failing to find/extract color decisions.  This isn't Walter's fault at all as I suspect writing data into EDL comments isn't very standardized.  I've submitted a pull request -- a slight tweak to the regexes -- that allow these EDLs to be parsed.

**Comment by ArrowThief** [comment]
Hey @heavyimage,
Thanks for responding despite how long its been. I had assumed it had something to do with EDLs not being standardized, but didn't know enough to fix it myself. If I ever need to convert ELDs to CDLs again I'll be sure to come back and try again.
